name = "banderaplaya"
pages_build_output_dir = "public"
compatibility_date = "2026-07-12"

# National beach cache, written by worker-scraper/ on a cron trigger, read
# here by /api/beaches. Pages Functions can't have cron triggers themselves,
# hence the separate standalone Worker.
[[kv_namespaces]]
binding = "BEACHES_CACHE"
id = "485813a5c0c24b3b9d73ea68c14252f7"
